### ISSUE TITLE
"Send" mode not working

### ISSUE THREAD

**Issue by LuisGP** [lemunozm/lancat#2]
```bash
➜  11:08:21 ~ lancat
error: The following required arguments were not provided:
    --listen

USAGE:
    lancat --discovery-ip <ip> --discovery-port <number> --listen --name <user name> --service-port <number>

For more information try --help
```

The same happens with `echo Hola | lancat`.

**Comment by lemunozm** [comment]
Hi @LuisGP, there was a problem with the *cli* already fixed at v0.2.0

**Comment by LuisGP** [comment]
Now it works using -w. To make `echo` + pipe work, I must add -w too. It is that correct?

**Comment by lemunozm** [comment]
Yeah :D, this is the new usage for writing into the LAN
